swagger: '2.0'
info:
  title: Shop API
  description: This is a product service for Enbook shop.
  version: 1.0.0
tags:
- name: product-service
  description: REST API for shop
paths:
  /products:
    get:
      tags:
      - Products
      summary: Get all products list
      operationId: getProductList
      description: Get all available products in the system
      produces:
      - application/json
      responses:
        200:
          description: Successful operation
          schema:
            type: array
            items:        
              $ref: '#/definitions/Product'
  /products/{productId}:
    get:
      tags:
      - Products
      summary: Find product by ID
      description: For valid response try ID with value. Other values will generated exceptions
      operationId: getProductById
      produces:
      - application/json
      parameters:
      - name: productId
        in: path
        description: ID of product that needs to be fetched
        required: true
        type: string
      responses:
        200:
          description: Successful operation
          schema:
            properties: 
              product:
                $ref: '#/definitions/Product'
        404:
          description: Product not found
definitions:
  Product:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      price:
        type: number
      count:
        type: integer
      description:
        type: string
schemes:
 - https
host: i6big9ofob.execute-api.eu-west-1.amazonaws.com
basePath: /dev